apiVersion: v1
kind: Service
metadata:
  name: submodel-editor-backend
  namespace: idta-editor
  labels:
    app.kubernetes.io/name: idta-submodel-editor
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: idta-submodel-editor
    app.kubernetes.io/component: backend
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
