apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: idta-editor-dev

resources:
  - ../../base

namePrefix: dev-

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: submodel-editor-backend
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: submodel-editor-frontend

configMapGenerator:
  - name: submodel-editor-config
    behavior: merge
    literals:
      - ENV=development
      - DEBUG=true
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173
